### PR TITLE
Substitute 'Clone' for 'Fork' in the image; fix #59

### LINKED ISSUE #59: Ex. a full-cycle collaborative workflow, image fix
Should the "cycle workflow image" have "Fork" & "Make pull request" instead of "Clone" & "Make pull request"?
This image: https://github.com/coderefinery/testing/blame/gh-pages/_episodes/05-gh-actions.md#L28

### PR DESCRIPTION
**Pull request by juholehtonen**

### CODE REVIEW

**Comment by juholehtonen** [comment]
Preview of suggestion:
testing_group_work

**Comment by juholehtonen** [comment]
Ah, description in the image needs editing perhaps: "Fork and clone one of your colleagues repository".

**Comment by bast** [comment]
Is it easy for you to edit the description? Because I agree that it can read confusing now.

**Comment by blindij** [comment]
I will correct the figure. (fork, clone etc...)

**Comment by blindij** [comment]
.. made a  PR with update figure.

**Comment by bast** [comment]
But where is the updated figure or the other pull request?

**Comment by bast** [comment]
This is marked as draft. I am unsure whether something is left to do. Something I can do to unblock this?

**Comment by bast** [comment]
What is the plan with this one? Should I pick it up from here?

**Comment by bast** [comment]
I am closing this PR since it's conflicting and stalled and the repo has moved on. @juholehtonen are the sources somewhere? How did you change the text? Or was it changed in a bitmap way?

**Pull request closed without merging**
