### PR TITLE
Fixed git pull

### PR DESCRIPTION
**Pull request by matuskalas**
* main branch may be undefined in a usual setup following the steps
* origin unnecessary. Or is there an educational reason for it in this case?

### CODE REVIEW

**Comment by matuskalas** [comment]
Could it be that `git pull origin main` didn't work for me because of old git version?
My git is `2.27.0.windows.1`

**Comment by bast** [comment]
I am surprised by this. Can it be that there was no `main` branch on origin and instead there was a `master` branch?

**Comment by matuskalas** [comment]
> I am surprised by this. Can it be that there was no `main` branch on origin and instead there was a `master` branch?

Indeed that was the case, because instead of
Screen Shot 11-30-20 at 02 08 PM

...I do just simple
```bash
git clone https://github.com/...
git add ...
git commit ...
git push
```

Btw., is doing the above potentially dangerous (other than wrt `main` _vs._ `master`)?

(For fun, no surprise that this happens if I this way clone an empty repo, then create a file directly on GitHub, and then push local changes:
Screen Shot 11-30-20 at 02 29 PM 001
)

Maybe the following is well-known, but anyhow as it sounded like a great procrastination when I should have been filling in some administrative forms, I tested it a bit around in git, finding out that:

- git version `2.26.2-0` ignores the `init.defaultbranch` config
- `2.29.2` uses `init.defaultbranch`, also when cloning an empty repo
- _Git for Windows_ updater/installer `2.29.2` asks about this
Screen Shot 11-30-20 at 02 03 PM

Afterall, I have 2 questions left:

- Would it be useful (until `main` becomes default in git) to add a requirement for having a "new enough" version of git and setting up `git config --global init.defaultbranch main` into the Git setup instructions? (https://github.com/coderefinery/installation/issues/147)
- (or) In this CI exercise, would it be enough with just `git pull` as I suggested in this PR, or is that a bad practice / not so educational?

**Comment by bast** [comment]
Very interesting! I think I never tried this:
```
git clone https://github.com/...
git add ...
git commit ...
git push
```
:-)

And I like your suggestion to define the default branch to avoid this and other mismatches.

**Comment by bast** [comment]
Discussion on chat makes clear that we should probably not change the default branch learner-side. Both because it may require upgrading Git which is out of reach for many and because it can make all examples on the web not work anymore.

**Comment by bast** [comment]
Sorry for picking this up late.

This situation "should not" happen if one follows "Before you create the repository, select “Initialize this repository with a README” (otherwise you try to clone an empty repo)."

But I know that this can be missed.

I will make that a bit clearer and also add a hint to the text that if the `git pull` fails, probably "wrong" branch was created and how to recover from it.

**Comment by bast** [comment]
I added a hint for this problem in #144. Closing this one since on chat we concluded that we cannot ask participants to configure a default branch locally and `git pull` alone can do different things depending on configuration.

**Pull request closed without merging**
