### PR TITLE
Changed pytest example to a TDD approach

### PR DESCRIPTION
**Pull request by blindij**
I made the pytest example more detailed, showing at Test-Driven Development approach. Could be that the time estimate is too short

### CODE REVIEW

**Comment by bast** [comment]
I think it is a good idea to show TDD but I would simplify the example even further so that it can be accomplished without Python knowledge and we don't have to spend (almost) any time on explaining Python. For instance implement a function that adds two or subtracts two numbers. Also the test should not use several asserts in one test because then you also don't have to comment out two, things will get simpler.

**Comment by bast** [comment]
But what I write above is not a requirement. If you prefer this code to go in, I don't want to be a blocker. I don't want to create extra work.

**Comment by blindij** [comment]
Don't mind being a blocker - it is more important that we get to discuss stuff before it is commited. I will take a closer look and see how it can simplified even more.

**Comment by blindij** [comment]
Should I then close the pull request - "Close and comment"?

**Comment by bast** [comment]
You can leave it open and add changes to it. Then our thought process can be read up by others and is not in two places.

**Comment by bast** [comment]
Closing for the moment but a reminder left in #17.

**Pull request closed without merging**
