### PR TITLE
python version of the yahtzee exercise; closes #154

### LINKED ISSUE #154: Add Python example for randomness exercise

### PR DESCRIPTION
**Pull request by bast**

### CODE REVIEW

**Comment by bast** [comment]
I should rename the functions to be more consistent with the text. Working on it ....

**Comment by wikfeldt** [comment]
nice! This python version now uses a fixed random seed and tests an exact integer number of Yahtzees for the "integration" test, while the exercise instructions are to test the actual distribution by running many trials and checking approximate agreement with the statistically expected 4.6%. What do you think, worth updating the solution? But I'm fine with keeping it like this too

**Comment by bast** [comment]
OK we should fix this but I am unsure whether I will have time today.

**Comment by wikfeldt** [comment]
same here, i'll merge now and raise an issue and we'll see what we can do

**Pull request merged**
