### PR TITLE
reorganize first steps 1-2 in continuous_integration.md

### PR DESCRIPTION
**Pull request by teemu-ruokolainen**
NOTE: The tabs are not rendering correctly for me locally, could this be checked?
- {.tabsets} is shown in the titles
- the text and code in tabs in Step 2 are rendered weirdly, couldn't fix it

Suggestion to reorganize first steps 1-2 in continuous_integration.md to make it a bit easier to follow after the introduction of the example repo:

1. Create a new repo OR fork an existing example repo
1.1. Instructions for creating and closing repo, adding files, git add / commit / push
1.2. Instruction for forking and cloning example repo

2.1. Run tests manually (locally)

Steps 3.-9. would remain as they are now.

The README.md of the example repo should be updated accordingly to take into account the step reorganizing.

### CODE REVIEW

**Comment by bast** [comment]
Thanks! Do the `tabset` need to be there? It seems to render well if I take them away.

**Comment by teemu-ruokolainen** [comment]
>Thanks! Do the tabset need to be there? It seems to render well if I take them away.

The {.tabset} in the titles? I copied them from the existing parts of the file but yeah, I tried to leave them out as well and it worked OK. I'm not sure what their function is.

The Step 2 part I didn't get working: it prints the text and code verbatim instead of rendering it.

**Comment by bast** [comment]
OK I will look at step 2. I did not browse carefully enough ...

**Comment by teemu-ruokolainen** [comment]
>OK I will look at step 2. I did not browse carefully enough ...

Sorry, it was a bit hard to explain. It is probably a really simple mistake but I just couldn't debug it.

**Comment by teemu-ruokolainen** [comment]
Thomas solved the rendering problem, turns out the tab contents are sensitive to indentation. The structure is OK, I will merge this.

**Comment by bast** [comment]
> Thomas solved the rendering problem, turns out the tab contents are sensitive to indentation. The structure is OK, I will merge this.

Ah. Great work. Thanks.

**Pull request merged**
